steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/translatenav/github.com/radbrt/shiny_cicd:$SHORT_SHA', '-t', 'gcr.io/translatenav/github.com/radbrt/shiny_cicd:latest', '.' ]

# Insert short sha image tag
- name: 'gcr.io/cloud-builders/gsutil'
  id: Buildsha
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.yaml.tpl | \
     sed "s/SHORT_SHA/${SHORT_SHA}/g" > deployment.yaml
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=shinyhampster'
  - 'PROJECT_ID=$PROJECT_ID'
  - 'SHORT_SHA=$SHORT_SHA'

# Deploy
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  - 'apply'
  - '-f'
  - 'deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=shinyhampster'
  - 'PROJECT_ID=$PROJECT_ID'
  - 'SHORT_SHA=$SHORT_SHA'
  
images:
  - 'gcr.io/translatenav/github.com/radbrt/shiny_cicd:$SHORT_SHA'
  - 'gcr.io/translatenav/github.com/radbrt/shiny_cicd:latest'
tags:
  - "cloudbuild"