steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/translatenav/github.com/radbrt/shiny_cicd:$COMMIT_SHA', '-t', 'gcr.io/translatenav/github.com/radbrt/shiny_cicd:latest', '.' ]
- name: 'gcr.io/cloud-builders/gke-deploy'
  args: ['run', '--image="gcr.io/translatenav/github.com/radbrt/shiny_cicd:$COMMIT_SHA"', '--location="europe-north1-a"', '--cluster="shinyhampster"']
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=shinyhampster'
  
images:
  - 'gcr.io/translatenav/github.com/radbrt/shiny_cicd:$COMMIT_SHA'
  - 'gcr.io/translatenav/github.com/radbrt/shiny_cicd:latest'
tags:
  - "cloudbuild"